"""add llm_model to app_settings

Revision ID: 398258e41eaf
Revises: d5716d6ee36f
Create Date: 2026-08-08 17:32:18.056009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398258e41eaf'
down_revision: Union[str, Sequence[str], None] = 'd5716d6ee36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (5 businesses already seeded); the model-level
    # default in src/models.py covers new rows going forward, so drop the server_default
    # afterward to keep the two in sync going forward rather than having two sources of truth.
    op.add_column(
        'app_settings',
        sa.Column('llm_model', sa.String(), nullable=False, server_default='groq:llama-3.3-70b-versatile'),
    )
    op.alter_column('app_settings', 'llm_model', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'llm_model')
    # ### end Alembic commands ###
